# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b49f0ee83cc9cb75e81668c25186a49632858f6c0b83d79e0e09338c08a761e6b294ebcc071f1df2b8a1363403f84a15a768f441b214df1005f6304bfeb8fb5c

test:
  secret_key_base: 72155c6fd9bdae20cfdedcd0ae2069d976f04aecfff114d0a8e7cc5a749e4eedfa5bc471b727a52c2427313395f2976a1cf997dadfa52abed94f685e5fd857f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
